USE [master]
GO

/****** Object:  Database [Clientes]    Script Date: 05/08/2016 16:47:38 ******/
CREATE DATABASE [Clientes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Clientes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLDEVELOPER\MSSQL\DATA\Clientes.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Clientes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLDEVELOPER\MSSQL\DATA\Clientes_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Clientes] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Clientes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Clientes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Clientes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Clientes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Clientes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Clientes] SET ARITHABORT OFF 
GO

ALTER DATABASE [Clientes] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Clientes] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Clientes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Clientes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Clientes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Clientes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Clientes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Clientes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Clientes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Clientes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Clientes] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Clientes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Clientes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Clientes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Clientes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Clientes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Clientes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Clientes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Clientes] SET RECOVERY FULL 
GO

ALTER DATABASE [Clientes] SET  MULTI_USER 
GO

ALTER DATABASE [Clientes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Clientes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Clientes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Clientes] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Clientes] SET  READ_WRITE 
GO

